### ISSUE TITLE
对接成功,但是只支持短文本

### ISSUE THREAD

**Issue by shenmadouyaowen** [moxiaoyyds/chatgpt_springboot#1]
对接成功,返回多几个字都提示服务器故障

![image](https://user-images.githubusercontent.com/12426724/218953953-958b22cc-e495-4acb-9bb9-6e300493893c.png)

**Comment by moxiaoyyds** [comment]
你好，关于这点的话，微信开放文档里面有写。
“微信服务器在五秒内收不到响应会断掉连接，并且重新发起请求，总共重试三次。假如服务器无法保证在五秒内处理并回复，可以直接回复空串，微信服务器不会对此作任何处理，并且不会发起重试。”
因为ChatGPT是国外的服务器，问的一些问题ai回答的较慢，所以在5秒内微信公众号没有收到响应，就会提示公众号提供的服务出现异常
![image](https://user-images.githubusercontent.com/87122321/218955770-945f88c2-885d-4ba0-9f01-34515c858178.png)

**Comment by shenmadouyaowen** [comment]
好的,谢谢大佬解答

**Comment by moxiaoyyds** [comment]
没关系的

**Comment by shenmadouyaowen** [comment]
可以记录本次通话,然后发送一个词唤醒回复刚刚的话语?

**Comment by moxiaoyyds** [comment]
你可以自己尝试一下
